### ISSUE TITLE
Unable to update engine version

### ISSUE THREAD

**Issue by dimpsey** [techservicesillinois/terraform-aws-rds#10]
Oracle releases quarterly major version upgrades.  The way the rds module is configured, the `engine_version` is ignored after initial apply of configuation.

```
lifecycle {
    ignore_changes = ["engine_version", "password"]
  }
```

Therefore, unable to update to latest major version via a `terragrunt apply`.

**Comment by JonRoma** [comment]
@dimpsey, disabling automatic major upgrades was by design because we reasoned that there could be breaking changes involved. However, we don't want to preclude intentional major version upgrades in Terraform, and this may need further thought. Major version upgrades should be possible to do from the console in the meantime.

@ddriddle, I think we probably ought to document some of the processes involved with managing databases (snapshot dump/load, etc.) so people know what is and is not supported, and what workflows the module supports.

Also, I think Terraform 0.12 will require removing the quotation marks in the `ignore_changes` list, but that's not something we need to worry about now.

Hopefully we can discuss that Friday if I am well enough to be working.

**Comment by JonRoma** [comment]
This is moot.
